import { type Metadata } from "next";

import { Manrope } from "next/font/google";
import "./globals.css";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";

import { QueryProvider } from "@/providers/ReactQueryClient";
import { Toaster } from "sonner";
import { ourFileRouter } from "./api/uploadthing/core";

const manrope = Manrope({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UNMU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body className={manrope.className}suppressHydrationWarning={true} >
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <Toaster richColors />
          {children}
        </body>
      </html>
    </QueryProvider>
  );
}
